[package]
name = "HTeaPot"
version = "0.1.0"
exclude = [
  "hteapot.toml"
]
license = "MIT"
keywords = ["HTTP", "HTTP-SERVER"]
description = "HTeaPot is a lightweight HTTP server library designed to be easy to use and extend."
homepage = "https://github.com/az107/HTeaPot"
repository = "https://github.com/az107/HTeaPot"
readme = "README.md"
categories = ["network-programming", "web-programming"]
authors = ["Alb Ruiz G. <me@albruiz.dev>"]


[dependencies]
