[package]
name = "hteapot"
version = "0.2.1"
exclude = [
  "hteapot.toml",
  "public/",
  "readme.md"
]
license = "MIT"
keywords = ["HTTP", "HTTP-SERVER"]
description = "HTeaPot is a lightweight HTTP server library designed to be easy to use and extend."
homepage = "https://github.com/az107/HTeaPot"
repository = "https://github.com/az107/HTeaPot"
readme = "readme.md"
categories = ["network-programming", "web-programming"]
authors = ["Alb Ruiz G. <me@albruiz.dev>"]

[lib]
name = "hteapot"
path = "src/hteapot.rs"

[[bin]]
name = "hteapot"


