[HTEAPOT]
port = 8081
host = "0.0.0.0" 
root = "public"
threads = 5
cache = true
cache_ttl = 3600 
[proxy]
"/test" = "http://example.com"
"/google" = "http://google.com"
# "/" = "http://ifconfig.co" # this will override all the proxys and local request 