apiVersion: v1
kind: PersistentVolume
metadata:
  name: mi-pv
spec:
  capacity:
    storage: 512Mi # Asegúrate de que el tamaño sea suficiente para ambos volúmenes
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/albertoruiz/Projects/HTeaPot/public"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
